---
- hosts: all
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: 
        name: nginx
        state: latest
    - name: nginx
      service:
        name: nginx
        state: started
